// Generated by https://quicktype.io

export interface Empleado {
    idEmpleado:          number;
    idProfesiones:       number;
    idMunicipioRes:      number;
    idMunicipioNac:      number;
    idDepartamentoNac:   number;
    idDepartamentoRes:   number;
    idPaisNac:           number;
    idPaisRes:           number;
    idIdentificacion:    number;
    idEstadoCivil:       number;
    idSexo:              number;
    idNacionalidad:      number;
    numIdentificacion:   string;
    numINSS:             string;
    codMinsa:            string;
    primerNombre:        string;
    segundoNombre:       string;
    primerApellido:      string;
    segundoApellido:     string;
    fechaNacimiento:     Date;
    edadIngreso:         string;
    email:               string;
    direccionDomiciliar: string;
    telefonoDomiciliar:  string;
    telefonoMovil:       string;
    fechaContrato:       Date;
    urlFoto:             string;
    activo:              string;
}
