// Generated by Juan mecanico

export class Orden {
    idOrden:        number;
    numeroOrden:    string;
    idEmpleado:     number;
    idPaciente:     number;
    idTipoServicio: number;
    idTipoOrden:    number;
    asistencia:     string;
    observaciones:  string;
    fechaOrden:     Date;
    activo:         string;
    fechaImprime:   Date;

    constructor(){
        this.idOrden = 0;
        this.numeroOrden = "";
        this.idEmpleado = 0;
        this.idPaciente = 0;
        this.idTipoOrden = 0;
        this.idTipoServicio = 0;
        this.asistencia = "";
        this.observaciones = "";
        this.fechaOrden =  new Date("2023-05-22 00:00:00.000000");
        this.activo = "";
        this.fechaImprime = new Date("2023-05-22 00:00:00.000000");
    }
}
