// Generated by Juan Mecanico

export interface Examen {
    idExamen:            number;
    idAreaLabServicio:   number;
    idMetodologia:       number;
    idCategoriaExamenes: number;
    idTipoMuestra:       number;
    idUnidadMedidas:     number;
    idTipoResultado:     number;
    descripcion:         string;
    descripcionCorta:    string;
    liscode:             string;
    conteo:              string;
    confidencial:        string;
    calculado:           string;
}
