// Generated by Juan mecanico

export interface Orden {
    idOrden:        number;
    numeroOrden:    string;
    idEmpleado:     number;
    idPaciente:     number;
    idTipoServicio: number;
    idTipoOrden:    number;
    asistencia:     string;
    observaciones:  string;
    fechaOrden:     Date;
    activo:         string;
    fechaImprime:   Date;
}
