// Generated by Juan Mecanico

export class Resultado {
    idResultados:     number;
    idExamen:         number;
    idOrden:          number;
    resultado:        string;
    observaciones:    string;
    procesado:        string;
    fechaProcesa:   Date;
    idUsuarioProcesa: number;
    validado:           string;
    fechaValida:      Date;
    idUsuarioValida:  number;

    constructor (){
        this.idResultados = 0;
        this.idExamen = 0;
        this.idOrden = 0;
        this.resultado = "";
        this.observaciones = "";
        this.procesado = "";
        this.fechaProcesa = new Date("2023-05-22 00:00:00.000000");
        this.idUsuarioProcesa = 0; 
        this.validado = "";
        this.fechaValida = new Date("2023-05-22 00:00:00.000000");
        this.idUsuarioValida = 0; 
    }
}
